<h1>Welcome to the CSV Section</h1>
<h3>In this section, you will learn more about how to read and write CSV files.</h3>
<h3>If you have any questions, please consult the teaching staff for further clarifications</h3>

In [ ]:
#open text.csv to write something and use an alias for the file so we can keep referring to it
#w overwrites existing content in the file so need to be more careful if there is already something written in it

#after executing the code, the content should be already written in the file
with open("text.csv", "w") as f:
  f.write("First Name,Last Name,Age\n") #gives the column names
  f.write("Melvin,Ng,19\n") #column data
  f.write("Yoong,Wai Kit,18\n") #column data

In [ ]:
#To read a csv file, we need to skip the column headings and the "," characters

#To store First Name, Last Name, Age
word = ""
with open("text.csv", "r") as f:
    #_ means we do not need the variable 
    _ = f.readline()
    while (1):
      char = f.read(1)
      if char == ',' or char == '\n':
        print(word)
        word = ""
      else:
        word += char
      if char == '':
        _ = f.readline() #go next line
      if not char:
        break

Melvin
Ng
19
Yoong
Wai Kit
18

In [ ]:
#We define a function to read CSV data
def read_csv(file, rows, cols):

  #Extract data from the csv file into a 2d-list

  list2d = [[[0] for _ in range(cols)] for _ in range(rows)]
  #to keep track of storing location
  row = 0
  col = 0
  #To store First Name, Last Name, Age
  word = ""
  with open(file, "r") as f:
      while (1):
        char = f.read(1)
        if char == ',' or char == '\n':
          list2d[row][col] = word
          if char == ',':
            col += 1
          if char == '\n':
            row += 1
            col = 0
          word = ""
        else:
          word += char
        if char == '':
          _ = f.readline() #go next line
        if not char:
          break

  return list2d
data = read_csv("text.csv", 3, 3)
data

[['First Name', 'Last Name', 'Age'],
 ['Melvin', 'Ng', '19'],
 ['Yoong', 'Wai Kit', '18']]

In [ ]:
#To write data to a csv file using a 2d-list

#In this example we will use the previous 2d-list and the 2d-list will be written into a new csv file
print(data)

#We define a function to write csv data
def write_csv_with_exist_data(file, data):
  with open(file, "w") as f:
    for row in range(len(data)):
      for col in range(len(data[0])):
        if col != 2:
          f.write(data[row][col] + ",")
        else:
          f.write(data[row][col] + "\n")

write_csv_with_exist_data("output.csv", data)

[['First Name', 'Last Name', 'Age'], ['Melvin', 'Ng', '19'], ['Yoong', 'Wai Kit', '18']]

In [ ]:
#Verify if the output is the same as the "text.csv" file
read_csv("output.csv",3,3)

[['First Name', 'Last Name', 'Age'],
 ['Melvin', 'Ng', '19'],
 ['Yoong', 'Wai Kit', '18']]

In [ ]:
#write data to csv file with input function
rows = int(input("How many rows do you want the csv to store:"))
cols = int(input("How many columns do you want the csv to store:"))

def write_csv(file, rows, cols):
  #generate a 2d list
  list2d = [[[0] for _ in range(cols)] for _ in range(rows)]
  with open(file, "w") as f:
    for row in range(len(list2d)):
      for col in range(len(list2d[0])):
        written_data = input("Enter a data:")
        if col != len(list2d[0]) - 1:
          f.write(written_data + ",")
        else:
          f.write(written_data + "\n")
  return list2d

list2d = write_csv("write_input.csv", rows, cols)

How many rows do you want the csv to store:2
How many columns do you want the csv to store:2
Enter a data:Fruit
Enter a data:Food
Enter a data:Apple
Enter a data:Nasi Lemak

In [ ]:
read_csv("write_input.csv", rows, cols)

[['Fruit', 'Food'], ['Apple', 'Nasi Lemak']]

In [ ]:
#extract data from a specific column
def extract_from_column(file, column, rows, cols):
  list2d = read_csv(file, rows, cols)
  for row in range(1, len(list2d)):
      for col in range(len(list2d[0])):
        if list2d[0][col] == column:
          print(list2d[row][col])

In [ ]:
extract_from_column("text.csv", "Age", 3, 3)

19
18

In [ ]:
#extract data from a specific row
def extract_from_row(file, specify_row, rows, cols):
  list2d = read_csv(file, rows, cols)
  for row in range(1, len(list2d)):
    if row == specify_row:
      for col in range(len(list2d[0])):
          print(list2d[row][col])
    else:
      continue

In [ ]:
extract_from_row("text.csv", 1, 3, 3)

Melvin
Ng
19

<h1>Exercise 1: Create a CSV file that contains 4 rows and 4 columns. Place any data you want for the 16 data entries. After writing the csv file, extract data first the 2nd column and then the 1st row.</h1>

In [ ]:
#Code your solution here